### ISSUE TITLE
Video Page

### ISSUE THREAD

**Issue by chukon** [rvcapps/niurvc#9]
- Create mobile web page with Google Sites for Video Page.

- See [Google Sites] (https://sites.google.com/site/niurvc/)
See [example](https://sites.google.com/site/ioscisapp/video) we use [CISAPP](https://itunes.apple.com/us/app/mycis/id723928008?mt=8&ign-mpt=uo%3D4)

[link](https://sites.google.com/site/niurvc/video)

- Add 5 videos to web page

- See below

See [link] (http://www.rvchourofcode.com/niurvc.html)

![videos](https://user-images.githubusercontent.com/3256516/29379539-6ecb999c-8288-11e7-8e81-3d5187817794.png)

**Comment by chukon** [comment]
Changing page name to Media (Chuck)
Layout with be photos & video. I suggest a video placed above logo and quality images places on right and left. When users tap on any of the images it goes to a slide show.

**Comment by chukon** [comment]
I won't be on campus for today. If you need help make a comment in issue on Github.

Until we get common spot web access make changes to the Google Video page.

**Comment by chukon** [comment]
Noah, I would like to have the Media page layout done by 9/7/17. Until you get the images from Abbye just use some placeholder images for now. 

Ok?

**Comment by MrxHouse** [comment]
Alright, I have time this weekend to work on it. I may have some questions about APIs and will follow you up if need be.

**Comment by MrxHouse** [comment]
It has been awhile due to scheduling and tasks. I have been reaching and teaching myself classes, variables, and APIs. I am not sure what videos you wish for me to add besides the one on the RVC Mass Com website. I have some questions tomorrow about writing it in native Swift, my output is lacking due to my development operations, my apologies. I am in the process of fixing it and finding a working compiler. I mainly work with C++, Java, and Python and not with Apple software.

Otherwise, I can add this today in one hour if you inform me of the videos. did Abbye ever provide the images yet? Do I need to email her?

**Comment by chukon** [comment]
Complete the media page with dummy photos for now.

**Comment by MrxHouse** [comment]
Completed.
